CREATE DATABASE SPORTS
go
USE SPORTS
GO
CREATE TABLE USUARIOS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR (100) NULL, 
APELLIDO VARCHAR (100) NULL, 
DNI int NULL,
EMAIL VARCHAR (100) NULL, 
CONTRASEÑA VARCHAR(100) NULL,
FECHANACIMIENTO DATE NULL,
PROFESOR BIT NULL DEFAULT 0,
TipoUser int null -- 1=> Comun 
					  -- 2 => Admin
)
GO 
CREATE TABLE MODALIDAD (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
MODALIDAD VARCHAR (100) NULL
)
GO
CREATE TABLE ACTIVIDADES (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
IDUSUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID),--Profesor
ACTIVIDAD VARCHAR (100) NULL,  
DIAS VARCHAR (500) null,
MODALIDAD INT FOREIGN KEY REFERENCES MODALIDAD(ID), 
FECHAINICIO DATE NULL, 
FECHAFIN DATE NULL, 
HORARIOINICIO VARCHAR(5) NULL, 
HORARIOFIN VARCHAR (5) NULL, 
PRECIO DECIMAL NULL, 
IMAGEN VARCHAR (1000) NULL
)
GO 
CREATE TABLE USUARIOS_ACTIVIDAD (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
IDUSUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID), 
IDACTIVIDAD INT FOREIGN KEY REFERENCES ACTIVIDADES (ID), 
PENDIENTE BIT NULL DEFAULT 1,
)


--Inserts Por Default 
Insert into MODALIDAD Values ('Presencial')
Insert into MODALIDAD Values ('Virtual')

-- ************** PROCEDIMIENTOS ALMACENADOS **************
Go
CREATE PROCEDURE SP_AGREGAUSUARIO (
@EMAIL VARCHAR (100),
@PASSWORD VARCHAR (100), 
@NOMBRE VARCHAR (100), 
@APELLIDO VARCHAR (100)
)AS BEGIN 

	DECLARE @cantidadUsuariosRegistrados INT 
	Select  @cantidadUsuariosRegistrados = ISNULL(count(ID),0) from Usuarios 
	IF @cantidadUsuariosRegistrados = 0 
		Insert into USUARIOS (NOMBRE,APELLIDO ,EMAIL, CONTRASEÑA, TipoUser) VALUES (@NOMBRE,@APELLIDO,@EMAIL, @PASSWORD, 2)
	ELSE 
	Insert into USUARIOS (NOMBRE,APELLIDO ,EMAIL, CONTRASEÑA, TipoUser) VALUES (@NOMBRE,@APELLIDO,@EMAIL, @PASSWORD, 1)
END

GO

CREATE PROCEDURE SP_AGREGARACTIVIDAD (
@IDPROFESOR INT, 
@ACTIVIDAD VARCHAR (100), 
@DIAS VARCHAR (500), 
@IDMODALIDAD INT,
@FECHAINICIO DATE,
@FECHAFIN DATE, 
@HORARIOINICIO VARCHAR (5), 
@HORARIOFIN VARCHAR(5), 
@PRECIO DECIMAL, 
@IMAGEN VARCHAR (1000)
)AS BEGIN 
	INSERT INTO ACTIVIDADES VALUES (@IDPROFESOR, @ACTIVIDAD,@DIAS, @IDMODALIDAD, @FECHAINICIO, @FECHAFIN,@HORARIOINICIO,@HORARIOFIN,@PRECIO,@IMAGEN)
END


GO 
CREATE PROCEDURE SP_LISTAACTIVIDADES AS BEGIN 
	SELECT A.ID as idActividad, IDUSUARIO AS IdProfesor, U.Nombre as nombreProfesor, U.Apellido as apellidoProfesor, M.Id as IdModalidad, M.Modalidad as nombreModalidad,Actividad,Dias,fechaInicio,fechaFin, horarioInicio,horarioFin,Precio,Imagen FROM ACTIVIDADES A INNER JOIN USUARIOS U ON U.ID=A.IDUSUARIO INNER JOIN MODALIDAD M ON M.ID=A.MODALIDAD
END

GO 
CREATE PROCEDURE SP_SOLICITUDINSCRIPCION (
@ID INT, 
@IDACTIVIDAD INT
)AS BEGIN 
	INSERT INTO USUARIOS_ACTIVIDAD (IDUSUARIO, IDACTIVIDAD, PENDIENTE) VALUES (@ID, @IDACTIVIDAD, 1)
END


GO 
ALTER PROCEDURE SP_LISTAMISINSCRIPCIONES (
@IDUSUARIO INT
) AS BEGIN 
SELECT U.ID AS IDUSUARIO, U.NOMBRE AS NOMBREUSUARIO,U.APELLIDO as APELLIDOUSUARIO,U.DNI as DNIUSUARIO, U.EMAIL AS EMAILUSUARIO, U.CONTRASEÑA as USUARIOCONTRASEÑA, U.FECHANACIMIENTO as USUARIOFECHANACIMIENTO,ACT.ID AS IDACTIVIDAD ,ACT.ACTIVIDAD as NOMBREACTIVIDAD, ACT.DIAS AS DIASACTIVIDADES,ACT.MODALIDAD AS IDMODALIDAD,M.MODALIDAD AS NOMBREMODALIDAD,ACT.FECHAINICIO AS FECHAINICIO, ACT.FECHAFIN AS FECHAFIN, ACT.HORARIOINICIO,ACT.HORARIOFIN, ACT.PRECIO,ACT.IMAGEN FROM USUARIOS_ACTIVIDAD UXA INNER JOIN USUARIOS U ON U.ID=UXA.IDUSUARIO INNER JOIN ACTIVIDADES ACT ON ACT.ID= UXA.IDACTIVIDAD INNER JOIN MODALIDAD M ON M.ID=ACT.MODALIDAD WHERE UXA.IDUSUARIO=@IDUSUARIO AND UXA.PENDIENTE=0
END

Go
create procedure SP_ASIGNAPROFESOR (
@IDUSUARIO INT
)AS BEGIN 
	UPDATE USUARIOS SET PROFESOR = 1 WHERE ID = @IDUSUARIO
END

GO
CREATE PROCEDURE SP_LISTAMISPENDIENTES (
@IDUSUARIO INT
) AS BEGIN 
SELECT U.ID AS IDUSUARIO, U.NOMBRE AS NOMBREUSUARIO,U.APELLIDO as APELLIDOUSUARIO,U.DNI as DNIUSUARIO, U.EMAIL AS EMAILUSUARIO, U.CONTRASEÑA as USUARIOCONTRASEÑA, U.FECHANACIMIENTO as USUARIOFECHANACIMIENTO,ACT.ID AS IDACTIVIDAD ,ACT.ACTIVIDAD as NOMBREACTIVIDAD, ACT.DIAS AS DIASACTIVIDADES,ACT.MODALIDAD AS IDMODALIDAD,M.MODALIDAD AS NOMBREMODALIDAD,ACT.FECHAINICIO AS FECHAINICIO, ACT.FECHAFIN AS FECHAFIN, ACT.HORARIOINICIO,ACT.HORARIOFIN, ACT.PRECIO,ACT.IMAGEN FROM USUARIOS_ACTIVIDAD UXA INNER JOIN USUARIOS U ON U.ID=UXA.IDUSUARIO INNER JOIN ACTIVIDADES ACT ON ACT.ID= UXA.IDACTIVIDAD INNER JOIN MODALIDAD M ON M.ID=ACT.MODALIDAD WHERE UXA.IDUSUARIO=@IDUSUARIO AND UXA.PENDIENTE=1
END